name: Create a package artifact

on:
  push:
    branches:
      - main  # You can specify branches for push events, e.g., main
  workflow_dispatch:  # A

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip the package
        run: |
          cd packages
          zip -qr ../sample-package.zip sample-package/*

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sample-package
          path: sample-package.zip