name: Build a package and deploy to a Martini instance

on: [push]

jobs:
  build_deploy:
    name: Builds and deploys a package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: rashedobaid/martini-build-package@Support-for-multiple-packages
        with:
          base_url: ${{ vars.MARTINI_BASE_URL }}
          access_token: ${{ secrets.MARTINI_ACCESS_TOKEN }}
          package_dir: packages/sample-package
